#!/usr/bin/env bash
set -euo pipefail

cd /opt/book-id-search

TS="$(date +%Y%m%d-%H%M%S)"
LOG_DIR="/opt/book-id-search/logs/health-check"
mkdir -p "$LOG_DIR"

export NO_PROXY="*"
export no_proxy="*"

# Invoke pnpm directly via its installed binary. This bypasses corepack's
# self-bootstrap (which fetches pnpm from a registry and fails when the
# registry is unreachable / blocked by an HTTP proxy chain). The path below
# was generated by corepack on initial install and is stable.
PNPM_BIN="/home/ubuntu/.local/share/pnpm/store/v11/links/@/pnpm/10.33.0/85a40e0fec3fc3b22c9a205879caa8e7940c2153063351f9f1178b9f8843d8c3/node_modules/pnpm/bin/pnpm.cjs"

if [ ! -f "$PNPM_BIN" ]; then
  echo "[health-check-cron] FATAL: pnpm binary not found at $PNPM_BIN" >&2
  exit 4
fi

node "$PNPM_BIN" health:check \
  --public-url https://books.conanxin.com \
  --expected-docs 5115734 \
  --server-ip 118.195.129.137 \
  --json reports/health-check-latest.json \
  --markdown reports/HEALTH_CHECK_LATEST.md \
  > "$LOG_DIR/health-check-$TS.log" 2>&1

STATUS=$?

# 保留最近 14 天日志
find "$LOG_DIR" -type f -name 'health-check-*.log' -mtime +14 -delete || true

exit "$STATUS"