import {randomUUID} from 'node:crypto';
import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {Pool} from 'pg';
import {createPostgresCandidateClaimStore} from './candidate-claim-store.js';
import {CandidateClaimIntegrityError,CandidateClaimScopeNotFoundError,ResearchIssueReadOnlyError} from '../application/candidate-claims.js';
import {ProjectReadOnlyError,IdempotencyConflictError} from '../application/research-issues.js';
import {hashCandidateClaimCreateRequest} from '../domain/candidate-claim.js';
const url=process.env.S32_M2B_TEST_DATABASE_URL;
const parsed=url?new URL(url):null;
if(parsed&&(parsed.hostname!=='127.0.0.1'||parsed.pathname!=='/s32_m2b_test'))throw new Error('M2-B integration requires isolated local s32_m2b_test');
const pool=url?new Pool({connectionString:url}):null;
afterAll(async()=>{await pool?.end();});
describe.skipIf(!pool)('M2-B real PostgreSQL16',()=>{
 const db=pool!;const store=createPostgresCandidateClaimStore(db);
 beforeAll(async()=>{expect((await db.query('SHOW server_version_num')).rows[0].server_version_num).toMatch(/^16/);});
 async function fixture(){const projectId=randomUUID(),issueId=randomUUID();await db.query("INSERT INTO core.projects(id,name) VALUES($1,'M2B fixture')",[projectId]);await db.query("INSERT INTO core.research_issues(id,title,question) VALUES($1,'Question','What happened?')",[issueId]);await db.query("INSERT INTO core.project_bindings(id,project_id,target_type,target_id) VALUES($1,$2,'RESEARCH_ISSUE',$3)",[randomUUID(),projectId,issueId]);return {projectId,issueId};}
 function input(f:{projectId:string;issueId:string},statement='Candidate A'){return {...f,claimId:randomUUID(),idempotencyKey:randomUUID(),statement,requestHash:hashCandidateClaimCreateRequest(f.projectId,f.issueId,statement)};}
 const scope=(f:{projectId:string;issueId:string})=>`S32:M2B:PROJECT_ISSUE_CLAIM_CREATE:${f.projectId}:${f.issueId}`;
 async function counts(f:{projectId:string;issueId:string}){return (await db.query(`SELECT (SELECT count(*)::int FROM core.claims c JOIN core.research_issue_claims r ON r.claim_id=c.id WHERE r.issue_id=$1) claims,(SELECT count(*)::int FROM core.research_issue_claims WHERE issue_id=$1) relations,(SELECT count(*)::int FROM ops.idempotency_keys WHERE scope=$2) receipts`,[f.issueId,scope(f)])).rows[0];}
 it('atomically creates a canonical claim, relation and completed receipt',async()=>{const f=await fixture(),a=input(f);const r=await store.create(a);expect(r).toMatchObject({status:'created',claim:{id:a.claimId,statement:a.statement,lifecycleState:'ACTIVE'}});expect(await counts(f)).toEqual({claims:1,relations:1,receipts:1});expect((await db.query('SELECT claim_type,subject_type,subject_id,metadata FROM core.claims WHERE id=$1',[a.claimId])).rows[0]).toEqual({claim_type:null,subject_type:null,subject_id:null,metadata:{}});expect((await db.query('SELECT status,resource_type,resource_id FROM ops.idempotency_keys WHERE scope=$1',[scope(f)])).rows[0]).toEqual({status:'COMPLETED',resource_type:'CLAIM',resource_id:a.claimId});});
 it('serializes concurrent same-key requests to exactly one claim',async()=>{const f=await fixture(),a=input(f);const r=await Promise.all([store.create(a),store.create({...a,claimId:randomUUID()})]);expect(r.map(x=>x.status).sort()).toEqual(['created','replayed']);expect(r[0].claim.id).toBe(r[1].claim.id);expect(await counts(f)).toEqual({claims:1,relations:1,receipts:1});});
 it('rejects a changed hash without adding rows',async()=>{const f=await fixture(),a=input(f);await store.create(a);await expect(store.create({...input(f,'Other'),idempotencyKey:a.idempotencyKey})).rejects.toBeInstanceOf(IdempotencyConflictError);expect(await counts(f)).toEqual({claims:1,relations:1,receipts:1});});
 it.each(['PROJECT_ARCHIVED','RESOLVED','ARCHIVED'])('replays after %s but gates new writes',async state=>{const f=await fixture(),a=input(f);await store.create(a);if(state==='PROJECT_ARCHIVED')await db.query("UPDATE core.projects SET lifecycle_state='ARCHIVED' WHERE id=$1",[f.projectId]);else await db.query('UPDATE core.research_issues SET lifecycle_state=$2 WHERE id=$1',[f.issueId,state]);expect(await store.list(f.projectId,f.issueId)).toMatchObject({claims:[{id:a.claimId}]});expect(await store.create({...a,claimId:randomUUID()})).toMatchObject({status:'replayed',claim:{id:a.claimId}});await expect(store.create(input(f))).rejects.toBeInstanceOf(state==='PROJECT_ARCHIVED'?ProjectReadOnlyError:ResearchIssueReadOnlyError);expect(await counts(f)).toEqual({claims:1,relations:1,receipts:1});});
 it('preserves cross-project privacy and namespace',async()=>{const a=await fixture(),b=await fixture();await expect(store.list(b.projectId,a.issueId)).resolves.toBeNull();await expect(store.create(input({projectId:b.projectId,issueId:a.issueId}))).rejects.toBeInstanceOf(CandidateClaimScopeNotFoundError);expect((await db.query('SELECT count(*)::int n FROM ops.idempotency_keys WHERE scope=$1',[scope({projectId:b.projectId,issueId:a.issueId})])).rows[0].n).toBe(0);});
 it('fails closed for multiple Issue owners',async()=>{const a=await fixture(),b=await fixture();await db.query("INSERT INTO core.project_bindings(id,project_id,target_type,target_id) VALUES($1,$2,'RESEARCH_ISSUE',$3)",[randomUUID(),b.projectId,a.issueId]);await expect(store.list(a.projectId,a.issueId)).rejects.toBeInstanceOf(CandidateClaimIntegrityError);await expect(store.create(input(a))).rejects.toBeInstanceOf(CandidateClaimIntegrityError);});
 it('fails closed for a dangling relation',async()=>{const f=await fixture(),claimId=randomUUID(),c=await db.connect();try{await c.query('SET session_replication_role = replica');await c.query('INSERT INTO core.research_issue_claims(issue_id,claim_id) VALUES($1,$2)',[f.issueId,claimId]);}finally{await c.query('SET session_replication_role = origin');c.release();}await expect(store.list(f.projectId,f.issueId)).rejects.toBeInstanceOf(CandidateClaimIntegrityError);});
 it('rolls back claim and reservation on relation-insert failure',async()=>{const f=await fixture(),a=input(f);await db.query(`CREATE FUNCTION core.m2b_test_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.claim_id='${a.claimId}'::uuid THEN RAISE EXCEPTION 'test relation failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER m2b_test_fail BEFORE INSERT ON core.research_issue_claims FOR EACH ROW EXECUTE FUNCTION core.m2b_test_fail()`);try{await expect(store.create(a)).rejects.toThrow('test relation failure');expect(await counts(f)).toEqual({claims:0,relations:0,receipts:0});expect((await db.query('SELECT count(*)::int n FROM core.claims WHERE id=$1',[a.claimId])).rows[0].n).toBe(0);}finally{await db.query('DROP TRIGGER m2b_test_fail ON core.research_issue_claims; DROP FUNCTION core.m2b_test_fail()');}});
 it('reads legitimate global non-null claim type and subject',async()=>{const f=await fixture(),id=randomUUID();await db.query("INSERT INTO core.claims(id,claim_type,statement,subject_type,subject_id) VALUES($1,'HISTORICAL','Historical candidate','WORK',$2)",[id,randomUUID()]);await db.query('INSERT INTO core.research_issue_claims(issue_id,claim_id) VALUES($1,$2)',[f.issueId,id]);expect(await store.list(f.projectId,f.issueId)).toMatchObject({claims:[{id,statement:'Historical candidate'}]});});
 it('reconstructs store and recovers list and completed replay',async()=>{const f=await fixture(),a=input(f);await store.create(a);const fresh=createPostgresCandidateClaimStore(db);expect(await fresh.list(f.projectId,f.issueId)).toMatchObject({claims:[{id:a.claimId}]});expect(await fresh.create({...a,claimId:randomUUID()})).toMatchObject({status:'replayed',claim:{id:a.claimId}});});
});
