// @vitest-environment jsdom
import {beforeEach,afterEach,expect,it,vi} from 'vitest';
import * as draft from './candidate-claim-draft';
const p='AAAAAAAA-AAAA-4AAA-8AAA-AAAAAAAAAAAA',i='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',other='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
beforeEach(()=>{vi.unstubAllGlobals();sessionStorage.clear();draft.clearPendingCandidateClaimReceipt();});
afterEach(()=>vi.unstubAllGlobals());
it('normalizes White_Space, CR/LF and enforces NUL/code-point bounds',()=>{expect(draft.normalizeCandidateClaimDraft(' \u0085a\r\nb\rc\t d ')).toBe('a b c d');expect(draft.normalizeCandidateClaimDraft('𠮷'.repeat(4000))).toHaveLength(8000);for(const s of ['\u0085','a\0b','𠮷'.repeat(4001)])expect(()=>draft.normalizeCandidateClaimDraft(s)).toThrow();});
it('matches server fixed-order Project+Issue+statement hash including NEL',async()=>{const {hashCandidateClaimCreateRequest}=await import('../../../api/src/s32/domain/candidate-claim');const s='\u0085a\r\nb\u0085c ';expect(await draft.hashCandidateClaimDraft(p,i,s)).toBe(hashCandidateClaimCreateRequest(p,i,s));});
it('rotates only for changed normalized intent, scope or explicit force',async()=>{const a=await draft.getOrCreateCandidateClaimReceipt(p,i,' a\nb ');expect((await draft.getOrCreateCandidateClaimReceipt(p.toLowerCase(),i,'a b')).idempotencyKey).toBe(a.idempotencyKey);const b=await draft.getOrCreateCandidateClaimReceipt(p,i,'other');const c=await draft.getOrCreateCandidateClaimReceipt(other,i,'other');const d=await draft.getOrCreateCandidateClaimReceipt(other,other,'other');const e=await draft.getOrCreateCandidateClaimReceipt(other,other,'other',true);expect(new Set([a,b,c,d,e].map(r=>r.idempotencyKey)).size).toBe(5);});
it('persists exactly five receipt fields without statement',async()=>{await draft.getOrCreateCandidateClaimReceipt(p,i,'private text');const raw=sessionStorage.getItem(draft.CANDIDATE_CLAIM_PENDING_KEY)!;expect(Object.keys(JSON.parse(raw)).sort()).toEqual(['createdAt','idempotencyKey','issueId','projectId','requestHash']);expect(raw).not.toContain('private text');});
it('stale valid A and denied B writes preserve B retry key',async()=>{const a=await draft.getOrCreateCandidateClaimReceipt(p,i,'A');const raw=sessionStorage.getItem(draft.CANDIDATE_CLAIM_PENDING_KEY);vi.stubGlobal('sessionStorage',{getItem:()=>raw,setItem(){throw Error('write denied');},removeItem(){}});const b=await draft.getOrCreateCandidateClaimReceipt(p,i,'B');expect(b.idempotencyKey).not.toBe(a.idempotencyKey);expect((await draft.getOrCreateCandidateClaimReceipt(p,i,'B')).idempotencyKey).toBe(b.idempotencyKey);});
it('clear tombstone survives failed remove',async()=>{await draft.getOrCreateCandidateClaimReceipt(p,i,'A');const raw=sessionStorage.getItem(draft.CANDIDATE_CLAIM_PENDING_KEY);vi.stubGlobal('sessionStorage',{getItem:()=>raw,setItem(){},removeItem(){throw Error('remove denied');}});draft.clearPendingCandidateClaimReceipt();expect(draft.loadPendingCandidateClaimReceipt()).toBeNull();});
it('fresh restore caches before later read failure',async()=>{const a=await draft.getOrCreateCandidateClaimReceipt(p,i,'A');vi.resetModules();const fresh=await import('./candidate-claim-draft');expect(fresh.loadPendingCandidateClaimReceipt()).toEqual(a);vi.stubGlobal('sessionStorage',{getItem(){throw Error('read denied');},setItem(){},removeItem(){}});expect((await fresh.getOrCreateCandidateClaimReceipt(p,i,'A')).idempotencyKey).toBe(a.idempotencyKey);});
it.each(['missing','invalid','unreadable'])('initial %s storage can recover later',async kind=>{const a=await draft.getOrCreateCandidateClaimReceipt(p,i,'A');const raw=sessionStorage.getItem(draft.CANDIDATE_CLAIM_PENDING_KEY);vi.resetModules();const fresh=await import('./candidate-claim-draft');vi.stubGlobal('sessionStorage',{getItem(){if(kind==='unreadable')throw Error();return kind==='missing'?null:'{bad';}});expect(fresh.loadPendingCandidateClaimReceipt()).toBeNull();vi.stubGlobal('sessionStorage',{getItem:()=>raw});expect(fresh.loadPendingCandidateClaimReceipt()).toEqual(a);});
