// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {CandidateClaims} from './CandidateClaims';
import {createCandidateClaim,listCandidateClaims,ProjectApiError} from './api';
import {clearPendingCandidateClaimReceipt,loadPendingCandidateClaimReceipt} from './candidate-claim-draft';
vi.mock('./api',async load=>({...await load<typeof import('./api')>(),createCandidateClaim:vi.fn(),listCandidateClaims:vi.fn()}));
const project={id:'11111111-1111-4111-8111-111111111111',name:'Project',lifecycleState:'ACTIVE' as const,readOnly:false};
const issue={id:'22222222-2222-4222-8222-222222222222',projectId:project.id,title:'Question',question:'When?',lifecycleState:'OPEN' as const,createdAt:'2026-09-21T00:00:00Z',updatedAt:'2026-09-21T00:00:00Z'};
const claim={id:'33333333-3333-4333-8333-333333333333',statement:'Candidate A',lifecycleState:'ACTIVE' as const,createdAt:issue.createdAt,updatedAt:issue.updatedAt};
beforeEach(()=>{vi.resetAllMocks();clearPendingCandidateClaimReceipt();vi.mocked(listCandidateClaims).mockResolvedValue({claims:[]});vi.mocked(createCandidateClaim).mockResolvedValue({claim});});
afterEach(cleanup);
function show(p=project,i=issue){return render(<CandidateClaims token="t" project={p} issue={i}/>);}
async function submit(){await screen.findByText('还没有可能答案。');await userEvent.type(screen.getByRole('textbox',{name:'可能答案正文'}),'Candidate A');await userEvent.click(screen.getByRole('button',{name:'添加可能答案'}));}
it('shows confirmed empty and canonical competing claims as plain text',async()=>{vi.mocked(listCandidateClaims).mockResolvedValue({claims:[claim,{...claim,id:'44444444-4444-4444-8444-444444444444',statement:'<script>Candidate B</script>'}]});show();expect(await screen.findByText('Candidate A')).toBeTruthy();expect(screen.getByText('<script>Candidate B</script>')).toBeTruthy();expect(document.querySelector('script')).toBeNull();expect(document.body.textContent).not.toMatch(/置信|首选|真相/);});
it.each(['project','RESOLVED','ARCHIVED'])('hides writes for %s but reads claims',async state=>{show(state==='project'?{...project,readOnly:true}:project,{...issue,lifecycleState:state==='project'?'OPEN':state} as typeof issue);expect(await screen.findByText('还没有可能答案。')).toBeTruthy();expect(screen.queryByRole('textbox')).toBeNull();});
it('successful create shows returned canonical claim and clears receipt/form',async()=>{show();await submit();expect(await screen.findByText('Candidate A')).toBeTruthy();expect((screen.getByRole('textbox') as HTMLTextAreaElement).value).toBe('');expect(loadPendingCandidateClaimReceipt()).toBeNull();expect(createCandidateClaim).toHaveBeenCalledOnce();});
it.each([new TypeError('network'),new ProjectApiError(500,'SECRET'),new ProjectApiError(503,'SECRET'),new ProjectApiError(502,'SECRET')])('freezes unknown draft and retries exact key and payload %#',async error=>{vi.mocked(createCandidateClaim).mockRejectedValueOnce(error).mockResolvedValueOnce({claim});show();await submit();const retry=await screen.findByRole('button',{name:'使用同一标识重试'});const box=screen.getByRole('textbox') as HTMLTextAreaElement;expect(box.disabled).toBe(true);await userEvent.type(box,'changed');expect(box.value).toBe('Candidate A');expect(loadPendingCandidateClaimReceipt()).not.toBeNull();await userEvent.click(retry);await screen.findByText('Candidate A');const calls=vi.mocked(createCandidateClaim).mock.calls;expect(calls[1].slice(0,5)).toEqual(calls[0].slice(0,5));expect(document.body.textContent).not.toContain('SECRET');});
it('requires explicit new intent after claim-specific conflict',async()=>{vi.mocked(createCandidateClaim).mockRejectedValueOnce(new ProjectApiError(409,'研究问题内容不一致','IDEMPOTENCY_CONFLICT')).mockResolvedValueOnce({claim});show();await submit();expect(await screen.findByText('创建请求标识与当前可能答案内容不一致。')).toBeTruthy();expect(createCandidateClaim).toHaveBeenCalledOnce();await userEvent.click(screen.getByRole('button',{name:'作为新的可能答案重新提交'}));await screen.findByText('Candidate A');const calls=vi.mocked(createCandidateClaim).mock.calls;expect(calls[1][3]).not.toBe(calls[0][3]);});
it.each([[400,'CLAIM_INVALID_INPUT'],[409,'PROJECT_READ_ONLY'],[409,'RESEARCH_ISSUE_READ_ONLY']])('clears receipt on definite rejection %s %s',async(status,code)=>{vi.mocked(createCandidateClaim).mockRejectedValue(new ProjectApiError(Number(status),'拒绝',String(code)));show();await submit();await screen.findByText('拒绝');expect(loadPendingCandidateClaimReceipt()).toBeNull();});
it('retries unavailable claims without treating errors as empty',async()=>{vi.mocked(listCandidateClaims).mockRejectedValueOnce(Error('SECRET')).mockResolvedValueOnce({claims:[claim]});show();await screen.findByText('可能答案暂不可用。');expect(screen.queryByText('还没有可能答案。')).toBeNull();await userEvent.click(screen.getByRole('button',{name:'重试可能答案'}));expect(await screen.findByText('Candidate A')).toBeTruthy();});
it('ignores late response after unmount and retains pending receipt',async()=>{let resolve!:(v:{claim:typeof claim})=>void;vi.mocked(createCandidateClaim).mockImplementation(()=>new Promise(r=>{resolve=r;}));const view=show();await submit();await waitFor(()=>expect(createCandidateClaim).toHaveBeenCalledOnce());view.unmount();resolve({claim});await new Promise(r=>setTimeout(r,0));expect(loadPendingCandidateClaimReceipt()).not.toBeNull();});
